version: '3.7'

services:
  backend:
    build: .
    container_name: backend
    restart: always
    env_file:
      - ./.env
    ports:
      - "80:8000"
  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data/
    depends_on:
      - backend

volumes:
  redis_data:
